name: "Grott"
description: "An inverter monitor for Growatt inverters"
version: "0.1.6"
slug: "grott"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:want
image: inwy/{arch}-addon-grott
codenotary: edwin@inwy.nl
options:
  verbose: true
schema:
  verbose: bool
ports:
  5279/tcp: 5279
ports_description:
  5279/tcp: "Port on which the Growatt inverters communicate with the company servers"