name: "Grott"
description: "A monitor for Growatt inverters"
version: "0.1.17"
slug: "grott"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:want
image: "ghcr.io/inwy/{arch}-addon-grott"
codenotary: "edwin@inwy.nl"
options:
  verbose: true
  mqtt_ip: "127.0.0.1"
  mqtt_port: 1883
  mqtt_user: "user"
  mqtt_password: "password"
schema:
  verbose: "bool"
  mqtt_ip: "str"
  mqtt_port: "port"
  mqtt_user: "str"
  mqtt_password: "password"
ports:
  5279/tcp: 5279
ports_description:
  5279/tcp: "Port on which the Growatt inverters communicate with the company servers"