name: "Grott"
description: "A monitor for Growatt inverters"
version: "0.8.0"
slug: "grott"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:need
image: "ghcr.io/ebosveld/{arch}-addon-grott"
codenotary: "notary@inwy.nl"
hassio_api: true
options:
  verbose: true
  pvoutput:
    enabled: true
    apikey: "APIKey"
    inverters:
      - system_id: "PVOutput System ID"
        inverter: "serial"
schema:
  verbose: bool
  pvoutput:
    enabled: bool
    apikey: str
    inverters:
      - system_id: str
        inverter: str
ports:
  5279/tcp: 5279
ports_description:
  5279/tcp: "Port on which the Growatt inverters communicate with the company servers"